"""make user email globally unique

Revision ID: 06c021004eac
Revises: c44d2b93873e
Create Date: 2026-08-12 23:15:59.069779
"""
from alembic import op
import sqlalchemy as sa


revision = '06c021004eac'
down_revision = 'c44d2b93873e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_table_comment(
        'users',
        existing_comment='email is unique per-tenant, not globally — see migration UniqueConstraint',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'email is unique per-tenant, not globally — see migration UniqueConstraint',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
