"""initial schema

Revision ID: c44d2b93873e
Revises: 
Create Date: 2026-08-11 23:14:58.708181
"""
from alembic import op
import sqlalchemy as sa


revision = 'c44d2b93873e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_templates',
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('layout_rules', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_templates_institution_name'), 'institution_templates', ['institution_name'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.Enum('trial', 'starter', 'pro', 'enterprise', name='subscriptiontier'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='email is unique per-tenant, not globally — see migration UniqueConstraint'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('statements',
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.Enum('text_pdf', 'scanned_pdf', 'image', name='sourcetype'), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('institution_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'needs_review', 'reviewed', 'failed', name='statementstatus'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statements_tenant_id'), 'statements', ['tenant_id'], unique=False)
    op.create_table('extraction_jobs',
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='jobstatus'), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_jobs_statement_id'), 'extraction_jobs', ['statement_id'], unique=False)
    op.create_index(op.f('ix_extraction_jobs_tenant_id'), 'extraction_jobs', ['tenant_id'], unique=False)
    op.create_table('transactions',
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('raw_date', sa.String(length=50), nullable=False),
    sa.Column('raw_description', sa.String(length=2000), nullable=False),
    sa.Column('raw_debit', sa.String(length=50), nullable=True),
    sa.Column('raw_credit', sa.String(length=50), nullable=True),
    sa.Column('parsed_date', sa.String(length=20), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_uncertain', sa.Boolean(), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('was_corrected', sa.Boolean(), nullable=False, comment='True if a human changed any field — feeds ml_training_samples'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    op.create_index(op.f('ix_transactions_tenant_id'), 'transactions', ['tenant_id'], unique=False)
    op.create_table('ml_training_samples',
    sa.Column('source_transaction_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('input_features', sa.JSON(), nullable=False),
    sa.Column('corrected_label', sa.JSON(), nullable=False),
    sa.Column('used_in_training_run', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_training_samples')
    op.drop_index(op.f('ix_transactions_tenant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_extraction_jobs_tenant_id'), table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_statement_id'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_index(op.f('ix_statements_tenant_id'), table_name='statements')
    op.drop_table('statements')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_institution_templates_institution_name'), table_name='institution_templates')
    op.drop_table('institution_templates')
    # ### end Alembic commands ###
